export const site = {
  name: "Jacksonville Floor Coatings",
  shortName: "JFC",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://jacksonvillefloorcoatings.com",
  description:
    "Designer resin flooring, metallic epoxy and premium garage floor coatings for Jacksonville, Nocatee, Ponte Vedra and Northeast Florida.",
  phoneDisplay: "(904) 000-0000",
  phoneHref: "tel:+19040000000",
  email: "hello@jacksonvillefloorcoatings.com",
};

export const primaryNav = [
  { label: "Residential", href: "/residential-resin-flooring" },
  { label: "Garage", href: "/garage-floor-coatings" },
  { label: "Metallic", href: "/metallic-epoxy-flooring" },
  { label: "Commercial", href: "/commercial-floor-coatings" },
  { label: "Finishes", href: "/finishes" },
];

export const finishCollection = [
  { name: "Pearl Stone", description: "Warm white movement with restrained graphite veining.", className: "finish-pearl", mood: "Soft / architectural" },
  { name: "Coastal Smoke", description: "Layered pearl, silver and charcoal with quiet depth.", className: "finish-smoke", mood: "Balanced / modern" },
  { name: "Champagne Vein", description: "Cream mineral tones with a subtle warm metallic trace.", className: "finish-champagne", mood: "Warm / refined" },
  { name: "Atlantic Stone", description: "Cool gray movement inspired by honed coastal limestone.", className: "finish-atlantic", mood: "Calm / contemporary" },
  { name: "Midnight Marble", description: "Deep charcoal field with controlled silver movement.", className: "finish-midnight", mood: "Dramatic / polished" },
  { name: "Ivory Cloud", description: "Low-contrast ivory and pearl for light-filled interiors.", className: "finish-ivory", mood: "Quiet / minimal" },
];

export type ServicePageData = { slug:string; eyebrow:string; title:string; intro:string; metaDescription:string; price?:string; applications:string[]; benefits:{title:string;body:string}[]; process:string[]; faqs:{q:string;a:string}[]; visualClass:string; };

export const servicePages: Record<string, ServicePageData> = {
  resin: { slug:"resin-flooring-jacksonville", eyebrow:"Designer Resin Flooring", title:"Resin flooring designed around the room — not just the slab.", intro:"Seamless resin floors for Jacksonville homes and commercial interiors, with custom palettes, controlled movement and a protective finish selected for how the space is actually used.", metaDescription:"Designer resin flooring in Jacksonville, FL for kitchens, living areas, studios, offices and commercial spaces. Custom metallic and seamless resin finishes.", price:"Designer collections are quoted by finish, condition and square footage.", applications:["Kitchens","Open living spaces","Home offices","Studios & salons","Retail","Hospitality"], benefits:[{title:"Designed, not improvised",body:"We select palette, movement and visual intensity before installation so the floor has a clear design direction."},{title:"Seamless surface",body:"A continuous finish can visually simplify large open spaces and remove grout-line interruption."},{title:"Built for the room",body:"Topcoat, sheen and slip profile are selected around traffic, cleaning, sunlight and the actual use of the space."}], process:["Consultation & room review","Finish and palette selection","Concrete evaluation","Mechanical preparation","Design coat installation","Protective finish & reveal"], faqs:[{q:"Is resin flooring only for garages?",a:"No. Decorative resin systems can be used in interior residential and commercial spaces when the substrate, system and finish are appropriate for the environment."},{q:"Will every floor look exactly the same?",a:"No. Movement-based resin floors are intentionally one of a kind. The goal is to reproduce the design language, palette and intensity — not a mechanically identical pattern."},{q:"Can you work around islands and open floor plans?",a:"Yes. The room layout is part of the design. Islands, transitions, doorways and sight lines influence how movement is placed."}], visualClass:"visual-pearl" },
  residential: { slug:"residential-resin-flooring", eyebrow:"Residential Resin Floors", title:"A custom floor can change the entire room.", intro:"For kitchens, open living areas, home offices and other interiors where the floor should feel like part of the design — not an afterthought.", metaDescription:"Residential resin flooring in Jacksonville and Nocatee for kitchens, living spaces, home offices and custom interiors.", price:"Signature residential resin floors are custom quoted.", applications:["Kitchens","Living rooms","Dining areas","Home offices","Laundry rooms","Creative spaces"], benefits:[{title:"Interior-first styling",body:"We design around cabinetry, wall color, natural light and furniture rather than choosing a coating in isolation."},{title:"Custom visual intensity",body:"Choose a soft, balanced or dramatic interpretation of the finish collection."},{title:"Easy visual continuity",body:"Seamless flooring can connect kitchens and open living areas without introducing another pattern of joints."}], process:["Room photos & measurements","Finish consultation","Sample approval","Concrete preparation","Decorative resin installation","Protective topcoat"], faqs:[{q:"Can resin flooring work in a kitchen?",a:"Yes, when the slab and coating system are appropriate. Kitchens are one of the main interior applications we are building the design collection around."},{q:"Can the finish be subtle?",a:"Absolutely. The brand is not limited to high-contrast metallic swirls. Many of the strongest interior designs use restrained movement and neutral palettes."},{q:"Do you move appliances and cabinets?",a:"Project access and exclusions are confirmed before scheduling. Permanent cabinetry is treated as part of the room geometry; appliance handling is quoted based on the project."}], visualClass:"visual-ivory" },
  garage: { slug:"garage-floor-coatings", eyebrow:"Garage Floor Coatings", title:"A garage floor that looks finished — and works hard every day.", intro:"Professionally prepared garage floor systems for Jacksonville, Nocatee and St. Johns County, including flake, quartz and refined solid-color options.", metaDescription:"Garage floor coatings in Jacksonville, Nocatee and St. Johns County. Professionally prepared flake, quartz and resin floor systems.", price:"Garage collections will publish clear starting ranges as local installs are standardized.", applications:["2-car garages","3-car garages","Workshops","Home gyms","Storage garages","Luxury garages"], benefits:[{title:"Preparation first",body:"The quality of the finished system starts with the slab. Existing coatings, cracks and surface condition are evaluated before installation."},{title:"Designed garage palettes",body:"Garage colors are selected to work with the home, cabinets and lighting — not just picked from a generic chip board."},{title:"Use-specific protection",body:"System selection accounts for vehicle traffic, hot tires, cleaning, UV exposure at the door and expected use."}], process:["Slab inspection","Mechanical preparation","Repairs where needed","Base / broadcast system","Scrape & detail","Protective topcoat"], faqs:[{q:"How long before I can use the garage?",a:"Return-to-service depends on the exact system and site conditions. Your written proposal will include the product-specific cure schedule."},{q:"Do you coat over an existing failed floor?",a:"Not blindly. Existing coatings are evaluated for removal and the slab is prepared for the selected system rather than relying on the failed layer underneath."},{q:"Do you offer more than flake?",a:"Yes. Flake is the practical everyday garage option, but quartz, solid-color and more design-forward systems can be specified when appropriate."}], visualClass:"visual-garage" },
  metallic: { slug:"metallic-epoxy-flooring", eyebrow:"Metallic Resin Floors", title:"Movement, depth and a finish that belongs to the space.", intro:"Custom metallic resin floors with controlled color placement and visual movement for residential interiors, studios, retail and statement spaces.", metaDescription:"Metallic epoxy and decorative resin flooring in Jacksonville, FL. Custom marble, stone and movement-based finishes for residential and commercial interiors.", price:"Metallic and signature designs are custom quoted by complexity and floor condition.", applications:["Designer kitchens","Open living","Showrooms","Salons","Retail","Studios"], benefits:[{title:"One-of-one appearance",body:"The movement is hand created, so each installation has natural variation while following an intentional palette and layout."},{title:"Named design collections",body:"Customers choose a finished look and intensity level instead of trying to build a floor from raw pigment names."},{title:"Controlled composition",body:"Major movement, quiet areas and focal points are planned around the room rather than distributed randomly."}], process:["Design selection","Room mapping","Surface preparation","Base field","Movement & accent placement","Protective finish"], faqs:[{q:"Is metallic epoxy the same as a garage coating?",a:"It can use related resin chemistry, but the design intent and installation process are different. Metallic interiors focus heavily on visual composition, movement and the finished room."},{q:"Can you copy a photo exactly?",a:"No responsible installer should promise an exact fluid pattern. We can target a palette, movement style, contrast level and overall design character."},{q:"Can you make it look like marble?",a:"Marble-inspired movement is possible, but we position it as a resin interpretation rather than pretending it is natural stone."}], visualClass:"visual-smoke" },
  commercial: { slug:"commercial-floor-coatings", eyebrow:"Commercial Resin Flooring", title:"A better-looking floor without ignoring what the business demands.", intro:"Resin and concrete coating systems for Jacksonville retail, studios, salons, offices, showrooms and other commercial interiors where appearance and performance both matter.", metaDescription:"Commercial resin flooring and floor coatings in Jacksonville for retail, offices, salons, studios, showrooms and business interiors.", price:"Commercial pricing is based on access, condition, system and project schedule.", applications:["Retail","Salons","Studios","Offices","Showrooms","Light commercial"], benefits:[{title:"Brand-aware design",body:"Color and finish can support the identity of the space instead of defaulting to industrial gray."},{title:"Project-specific systems",body:"Traffic, cleaning routines, downtime, sunlight and slip needs are considered before choosing the coating build."},{title:"Clear scope",body:"Preparation, repairs, finish, cure expectations and exclusions are documented before the project starts."}], process:["Site review","System recommendation","Scheduling plan","Preparation","Installation","Handover & care"], faqs:[{q:"Do you work around business hours?",a:"Scheduling needs are reviewed during estimating. The feasible installation window depends on the system, cure requirements and access."},{q:"Can commercial floors still look custom?",a:"Yes. Commercial does not have to mean industrial. Decorative systems can be appropriate for customer-facing spaces when the performance requirements allow it."},{q:"Do you handle warehouses?",a:"The initial focus is residential and design-forward light commercial work. Larger industrial projects are evaluated individually so we do not oversell capability before the operation is built for them."}], visualClass:"visual-atlantic" }
};
