import type { LearningSource } from "./types";

export const learningSources: Record<string, LearningSource> = {
  icriCsp: {
    id: "icriCsp",
    name: "Concrete Surface Profile (CSP) guidance",
    publisher: "International Concrete Repair Institute (ICRI)",
    url: "https://www.icri.org/resources/icri-technical-publications/r3-concrete-guides/",
    note: "Industry guidance for evaluating and preparing concrete surfaces."
  },
  astmF2170: {
    id: "astmF2170",
    name: "ASTM F2170 — Relative Humidity in Concrete Floor Slabs",
    publisher: "ASTM International",
    url: "https://store.astm.org/standards/f2170",
    note: "Standard method for in-situ relative-humidity testing of concrete slabs."
  },
  astmD4263: {
    id: "astmD4263",
    name: "ASTM D4263 — Plastic Sheet Method for Concrete Moisture",
    publisher: "ASTM International",
    url: "https://store.astm.org/d4263-24.html",
    note: "Indicator method for capillary moisture before coating concrete."
  },
  sikaPrep: {
    id: "sikaPrep",
    name: "Surface Preparation Guide for Resinous Flooring",
    publisher: "Sika USA",
    url: "https://usa.sika.com/en/construction/floor-wall/resource-center/guides/surface-prep-guide.html",
    note: "Manufacturer guidance on soundness, contamination and concrete preparation."
  },
  sherwinPrep: {
    id: "sherwinPrep",
    name: "Floor Coating Surface Preparation",
    publisher: "Sherwin-Williams",
    url: "https://www.sherwin-williams.com/architects-specifiers-designers/floor-coatings-interior/resources/surface-preparation",
    note: "Concrete cure, contamination, moisture and preparation guidance."
  },
  sherwinPoly: {
    id: "sherwinPoly",
    name: "Polyaspartic Flooring — Features and System Chemistry",
    publisher: "Sherwin-Williams High Performance Flooring",
    url: "https://industrial.sherwin-williams.com/na/us/en/resin-flooring/resources/systems-chemistry/polyaspartic-floor-coatings.html",
    note: "Overview of cure speed, abrasion resistance, UV stability and decorative options."
  },
  sikaUv: {
    id: "sikaUv",
    name: "UV-Resistant Urethane and Polyaspartic Floor Coatings",
    publisher: "Sika USA",
    url: "https://usa.sika.com/en/construction-products/flooring/flooring-products/urethane-uv-resistant-coatings.html",
    note: "Manufacturer catalog of UV-resistant aliphatic urethane and polyaspartic systems."
  },
  sika700: {
    id: "sika700",
    name: "Sikafloor-700 Application Data",
    publisher: "Sika USA",
    url: "https://usa.sika.com/en/construction/floor-wall/flooring-products/chemical-resistant-coatings/sikafloor-700.html",
    note: "Product-specific examples of humidity, dew-point and substrate-moisture limits."
  },
  oshaSilica: {
    id: "oshaSilica",
    name: "Respirable Crystalline Silica — Construction Overview",
    publisher: "Occupational Safety and Health Administration",
    url: "https://www.osha.gov/silica-crystalline",
    note: "Safety guidance for silica generated by grinding and cutting concrete."
  },
  oshaGrinding: {
    id: "oshaGrinding",
    name: "Control of Silica Dust in Construction: Floor Grinders",
    publisher: "Occupational Safety and Health Administration",
    url: "https://www.osha.gov/sites/default/files/publications/OSHA3932.pdf",
    note: "Dust-control guidance for walk-behind floor grinders and milling machines."
  },
  nioshGrinding: {
    id: "nioshGrinding",
    name: "Control of Crystalline Silica Dust When Grinding Concrete",
    publisher: "NIOSH / CDC",
    url: "https://www.cdc.gov/niosh/engcontrols/ecd/detail2.html",
    note: "Engineering-control research on grinder shrouds, hoses and HEPA-filtered vacuums."
  },
  concretePaintVsEpoxy: {
    id: "concretePaintVsEpoxy",
    name: "Garage Floor Paint vs. Epoxy Coatings",
    publisher: "Concrete Network",
    url: "https://www.concretenetwork.com/concrete/garage_floor/paint-vs-epoxy-coating.html",
    note: "Consumer comparison of paint and two-component epoxy coating systems."
  },
  concreteBestCoating: {
    id: "concreteBestCoating",
    name: "Best Garage Floor Coating: Epoxy, Polyurea or Polyaspartic?",
    publisher: "Concrete Network",
    url: "https://www.concretenetwork.com/concrete/garage_floor/best-coating.html",
    note: "Industry overview comparing resin chemistries, cure speed, UV exposure and moisture considerations."
  },
  concreteEpoxy: {
    id: "concreteEpoxy",
    name: "Concrete Epoxy Floor Coatings",
    publisher: "Concrete Network",
    url: "https://www.concretenetwork.com/overlays-resurfacing-buyers-guide/epoxy.html",
    note: "General epoxy-floor overview covering preparation, design and consumer cost ranges."
  },
  concreteCost: {
    id: "concreteCost",
    name: "Concrete Flooring Cost Guide 2026",
    publisher: "Concrete Network",
    url: "https://www.concretenetwork.com/concrete/interiorfloors/cost.html",
    note: "National planning ranges for basic and decorative concrete floor finishes."
  },
  rustoleumGarage: {
    id: "rustoleumGarage",
    name: "EpoxyShield Garage Floor Coating Instructions",
    publisher: "Rust-Oleum",
    url: "https://www.rustoleum.com/~/media/DigitalEncyclopedia/Documents/RustoleumUSA/instruction-sheets/Epoxyshield_garage_floor_instructions.ashx",
    note: "Consumer-product instructions illustrating cure, temperature, humidity and new-concrete limits."
  },
  garageExpertsJax: {
    id: "garageExpertsJax",
    name: "Residential Floor Coatings in Jacksonville",
    publisher: "GarageExperts of Jacksonville",
    url: "https://www.garageexperts.com/jacksonville/epoxy-polyaspartic-flooring/residential-epoxy-flooring/",
    note: "Local-market reference for Jacksonville climate positioning and hybrid epoxy/polyaspartic systems."
  },
  jaxEpoxyFaq: {
    id: "jaxEpoxyFaq",
    name: "Jacksonville Epoxy — Flooring FAQs",
    publisher: "Jacksonville Epoxy",
    url: "https://jacksonvilleepoxy.com/faqs",
    note: "Local-market reference for common buyer questions about prep, moisture, cracking and UV exposure."
  },
  jaxEpoxyCost: {
    id: "jaxEpoxyCost",
    name: "Epoxy Flooring Cost in Jacksonville",
    publisher: "JAX Epoxy Floors",
    url: "https://jaxepoxyfloors.com/blog/epoxy-flooring-cost-jacksonville",
    note: "Local contractor pricing reference; use as market context rather than a universal price standard."
  },
  epoxyLocatorJax: {
    id: "epoxyLocatorJax",
    name: "Garage Floor Coating in Jacksonville, FL",
    publisher: "EpoxyLocator",
    url: "https://epoxylocator.com/jacksonville-fl/garage-floor-coating",
    note: "Jacksonville planning ranges and buyer questions; not a technical standard."
  },
  apexCost: {
    id: "apexCost",
    name: "Epoxy Garage Floor Cost 2026",
    publisher: "Apex Flooring",
    url: "https://apexflooringllc.com/epoxy-garage-floor-cost-2026-pricing-breakdown/",
    note: "Regional contractor pricing examples across Florida and the Southeast."
  },
  helloGarage: {
    id: "helloGarage",
    name: "Polyaspartic vs. Epoxy Floor Coatings",
    publisher: "Hello Garage",
    url: "https://www.hellogarage.com/blog/comparing-polyaspartic-and-epoxy-garage-floor-coatings/",
    note: "Large contractor/franchise comparison; product claims should be weighed against manufacturer data."
  },
  noaaJax: {
    id: "noaaJax",
    name: "Jacksonville 1991–2020 Climate Normals",
    publisher: "NOAA National Centers for Environmental Information",
    url: "https://www.ncei.noaa.gov/access/services/data/v1?dataset=normals-monthly-1991-2020&endDate=9996-12-31&format=pdf&startDate=0001-01-01&stations=USW00013889",
    note: "Official Jacksonville climate normals, including monthly precipitation and temperature context."
  },
};

export function resolveSources(ids: string[]): LearningSource[] {
  return ids.map((id) => learningSources[id]).filter(Boolean);
}
